### ISSUE TITLE
Ändern des Ausschnitts lädt Haltestellen neu

### ISSUE THREAD

**Issue by weberius** [codeforcologne/PublicDepartCologne#9]
Mit Aufruf der Applikation werden zunächst die nächsten fünf Stationen um den Standort ermittelt, per REST abfragt und auf der Oberfläche angezeigt. Mit Änderung des Zoom-Level oder des Standortes sollen alle Haltestellen im Rahmen der Bounding Box geladen werden. Diese werden auf der Oberfläche angezeigt.

**Comment by muescha** [comment]
Beim Anzeigen der 5 nächsten Stationen (Radius) könnten Stationen in der Map fehlen (Rechteck)


Besser:

Bei Start: 
1) ermitteln einer initialen BoundBox anhand der 5 nächten Stationen (oder max 2km)
2) Anzeige der Map anhand der optimalem Boundbox
3) ermitteln und Anzeige aller Haltestellen innerhalb der aktuellen BoundBox

Beim Scrollen/Zoomen dann wieder Punkt 3 ausführen

PS:

A) Evtl schon bei Punkt 1 auch die 5 Stationen übertragen und anzeigen, damit der Benutzer schon mit diesen beschäftigt ist, falls sehe viel mehr Haltestellen bei Punkt 3 geladen werden 

B) alternativ bei Punkt 3 die Stationen portionsweise übertragen (paging) oder streamen, damit bei großen Datenmengen die Anzeige nicht einfriert, sondern kontinuiertlich aktualisiert wird

**Comment by weberius** [comment]
Implemented; Es werden nun alle Stationen innerhalb des Bildschirms geladen. Wird die Anzeige verändert, werden die entsprechenden Stationen nachgeladen.
